/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Akshat (https://sketchfab.com/shooter24994)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-41fc80d85dfd480281f21b74b2de2faa
Title: Earth
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { a } from "@react-spring/three";
import { Mesh } from "@react-three/fiber";

const Earth = (props) => {
  const earthRef = useRef();
  const { nodes, materials } = useGLTF("/earth.glb");
  return (
    <a.group ref={earthRef} {...props} dispose={null}>
      <Mesh
        geometry={(nodes.Sphere_Material002_0 as Mesh).geometry}
        geometry={(nodes.Sphere_Material002_0 as Mesh).geometry}
        material={materials["Material.002"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </a.group>
  );
};

useGLTF.preload("/earth.glb");

export default Earth;
